{{- if eq .Release.Namespace "development" }}
apiVersion: v1
kind: Pod
metadata:
  name: policy-rejection-latest
  labels:
    purpose: policy-rejection-test
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
    - name: test
      image: busybox:latest
      command: ["sleep", "600"]
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
{{- end }}
