---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway-secret
  namespace: development
spec:
  encryptedData:
    JWT_SECRET: AgBB68w8E7hz2ADd/YdjCP9pSuaiFIIqoF8Z7LS9bDYsDZSF90S6Qx/VNUpC45WEp4DsYVwDpHU2EzNyzx9FXNnz26uwvF2ESGiXN7x4KI9847jGY4bs1p2SXo0OFNyOvsDsD/K/8arHPc8opMOI+CdaS87XFArrtEcDDxEawy0qBhbsPKUTr+Kud9JJ82UzERrYO4sTj8AZCi0UonxfWA2tQ2dRYZ8FvD2W/46qy/62aGUO4MEsE74H/sYcCaV0wqVF5+GEb0GYv9TxD2VMI2GnAl3K6FX8qsHb/w19OxW0ivIc/xJ4q2/JzrA1PAYin9csVtI3TOaRPRFXCiT5ZXccY4LAjTNdgcxc6+bI5QQKx/M+tJoFgZgz5DSg58ehRYfhdCeSoOEcqE+AWulPasAtRolPumsczTaKVY2Zy9DnTJLI6HmNRI5b2kUMnQjKtqXVmVKiAc9wT6m66ShQzh3OqbovdEstaNmG6CTO+mgiDboR7eduC1TIbDTdpzY/vUHoExq+mK+8PSWxtIEF0TXW41LxfBd08niAq+rp4+C6r34ipe23s6qiHLy9AxrlQbj6uP8K/jz20HpLDu/rnktMRcU1J6elOx6XzkpYRtmis1qkrdJvukyjuvNm5tuwpb5iAtaNOXiD8eNlGWHRmBvMPPaANRtJiCluOcP2+SZmvz3EQ5Q9gD0wlWisxWXJO31G2RzzjFAmRLz2AnUa6ZAcUjHhZYYtHKrTlNs5Uh6E7DVZy/CXK1ukibBw01m8MnOOg3IMxThQvSQbPNgJuvpN
  template:
    metadata:
      name: api-gateway-secret
      namespace: development
