---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cron-insert-secret
  namespace: development
spec:
  encryptedData:
    DATABASE_URL: AgB8yC3SIIlxEDVFSD77vrze1B6NLTDwLKFYkbaScvEdnvrActcZUa9Drypw3jDr2ze1aZXOjf+AnbyC2pT2Fb/bbnnhYvscgpSS44s+MD/S68sCsDH6Cbk3kgKx9VzrlPKHc1KUYI5mjbHjet97bnJlX+iqyvA7fzqrd59WlH8vcGRED7keEjxcx91Ds2ZeWzq4pJ+es0Dc0OWAHy+xzl3FM9FN8ViQPLnLn92iTLE6RxcAkO1eGiG2S8mkmpYKJFde4/cejo8Rx8Mlb9IgrmauRO+eiubEwR/Q6w8NuJ/L4W4QbkrpAQxojdjK03arcSaVArrStzMRrUY+VpUfcVC9amY++JiB6HQcPWn3s5LIYwMDhSSdyZhHCm/bAiBcI4zu3yAmYq7wyU5s8GUV5KKiVFpYyePlLNsY+RfE1kU7drSUscbv2DFFKVdJXWbT1GAPUCveXhmyVjwfD4BxmChfEf+jVsbRUBaexQX5ESCvuc8OzUawX8SdKV6GPBKy2FBI1vDebrGeeh0NJpdX7zvyOIspKNut4Bji9WNBYXK+H7vXM+WsmCbRD/GDjiT6yyiqLnmxLdPKjLFeFk5ZFhBOZBDuNDU3QixfFvhr2QEb49XmZSoQbBU+ncsrV+d7+SNV2LWoMDyPcahu70cB2iDk3e7vOTPbdHLH4Yajak10zjP54Rnhis5Z6fIWC6n5Ew4mPds/hixcos8Do7AxhBqs2e3eYlyKRwUfK/jeGWwOh9QJdOGxbmSyBaCf9YhXvmgFMYPyFQwqxfOnLuHoMkIIN45wU5VGct2o/SbPwvzTdb0I2TGd72QdT5y5OzL+NYRBgCXLDEukec2e39EG8Jg9EjI0BhNsTrVb+xeqkQZBe4c4cohNMg==
  template:
    metadata:
      name: cron-insert-secret
      namespace: development
