---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: development
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgAtOD7fiDR00q8H93IiLbk8ZaXrtAS906WncmldRc6K3ycyj7PTN/yDcsrmezbN0/Ey3qFpSnVR2vSXE7oME3+J2gSiGDwpzDDTnQryjON+YZrg7bXb1/oFYE/imoLjFD9hnbp201LHBNc4x+HdefJDAeZ66ZqOUgkD3uCIOypXMhANVDrHoAwBrCxoZ4dV6TG11KCDOPZuo8skYRfBZfdncFb3Udh6TFdYSrxCUBFotZRPGynFhJcw5VJ229HxPheK/QC6KnFyA7MoOH+DqZB42MIZql/vfrpnuMuvBNyY4Vs2BiFfr6DFsb4bhNJvkxVUofhAqAGytxQrwCUjDb48osV3mwXgqVVkKuA7bm0PxEhDl13n7YmPGEyGASc2a9uQUDECGrY2eqWa37ZNOvvOTYvBTe65MSWnkuGZXWjWxQMVl6TeI/9joxUOuimWURZcGsmswk9ifx3lQR4vnaZtGp6NHe1RUGYaAHxzIDx3h//QFh6+EII6OyEAINTusvwob3Z0sETxbfaGZnfHxs96s3EKeJ8S/HVI2QmV9CNmsgVMS+ZALav8p8OqSC8sdcopLHDTPNK6CstRCPKUeUssmSOM9Ch7bxzA0HAM2XRzL+Ol43S3febwwv/HI4i87vP5e3ScewkrsarWRy3BNuBIVRzJe/iGNW9K4jRjjWeuTObYkNrDqWZz9hRrA29muGKHupIa2z9pO8xVUAumUeWR8PvnMKxhvrC98zlboxyvKFLzxtX29dkBlwrx4qa51k4=
    RABBITMQ_USER: AgC/iWxGjDNSGkz5E2yz58G+mdyQEp4asqQ8mrhiW+HQOKsCBEjKqxk/gq/pLSY8oejN51fBZi/VwPjvnz9YS3aYzeHG3PocPKYV5MzFvCexIg1Xnxecjq1JrmisKxJzoyHeWF+3nZ3P4x+Hoy5rImdMU2VVgLxOaHAS7dEyAm1pojegwm9xpsY2d4JNeb4MpELIksRag4YCEFqlZKf0bUuKC/l92rRLPkP0V9ZpPBmpBtqB/XKlgvXYRjUnU9GAmhPEHiAj1G4mrBZ6Ii1ZjSrVq4L7tDhkTyOrAox4nZEqwrDuoCb9eFler6OhKTe4LhZG7v7hKyohjgkRRnaTfmu83dP84GLYvFVa+8X2oI7uivBeMZwtzccfNbREC2skMQUcbassB4849/E3IgF5ul1hfXdObZPRaeagy5GsZGqGKUPYsUxlwJqF9B5+j/KorMC6Jj1w6zCA5lIWhOOz50r4e8dIy7vq8YsGD41Z4aiUVOiN/FLT+oHgrpPSEIlIS6UpIlZeqPM70HlYl2XEd2h2irfF03TUEb+xBA1rL6Z83PbMt7IQMFAdoHGpUwsp/hbkbQ3V4j7ElSmvD7UiHD8haYa8Jka+KnFzJjB5q8yswvoQJrjWTlGOK1X4UDe7usA2BQAIVfMCllWHDzXgPgUt0hI6oxgJfLYVhOabhKWsULc1Mo05Z7y5eVkcuMgXrPCqh5PQvZ6E
  template:
    metadata:
      name: rabbitmq-secret
      namespace: development
