replicaCount: 1
image:
  tag: "1.0.8"
config:
  APP_VERSION: "1.0.8"
  LOG_LEVEL: info
hpa:
  minReplicas: 1
  maxReplicas: 2
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 320Mi
