---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway-secret
  namespace: production
spec:
  encryptedData:
    JWT_SECRET: AgAR9GlslLO96YTmFJ0aFkec6SIf1Q37bM+go1LCzUiuFgIqFoOE8Zj3SXIbLeNXtTEq+agYe4BJ15msLyaMFttZvZi1JFAko1eau5euOXvPEhNO/EgrJOnimsloOWTOh8oizDiliHnesQqjnOj1FfsQZKBICXheptxEO2LHm31aiBsGpioFRW+0sErAOqdqTj+RBGd0dYnoN+SdImaQPiOwEpH0/uMm0fQdG5k0rQBvKSJV0cMzXjKI1btLSG2JqONnjUUaTpbHTQB/JvuSVY4s2vZaC2LqjFClf4nt5FIFHZAccCxSxDZy0wU0miLPunOy30zEkPdrF+8Hxa7/mkWIqL3XS4ap+BUxbrlYSRvqNo8bE6NgUeFJVgFPjVVAJmm7jKiKN3ClSjJL0k5U2wfvCa7rrbObiyRw7J5Y5lIgKSYIDs02z/4Cyu4EzQRzZ59YKJ3RWwXDs9tZ3O1RD75RECUXNzF7/ddqHOnasyED4ZgSxI2INfmqmSqJMwW8DonBQ7CILUxipit2kIjXJm1o67NZrH13RcLQpIwrXtyFsU9zVWqKx0DDXlfWRH3EPHFtFQ0RKtjNID3EuOnbg3YLAS50HLowoxzwZWmn6M+ZQu+uxsLXW/vyGmJWsDt42NfATngDBfqJ4THcBUNoCUTOobE5IWD8j2aC6ZIig9lJG5GfPE9m0ZwVRbVVR7yTJBEtg9xVfDWbFn19qFpYOdGeN/Ejqyta2s/CsLmoJrmeRHhcXgdHMnhkOFiK5aF0yEVFjk57bTh6D/oEop+CQoW4
  template:
    metadata:
      name: api-gateway-secret
      namespace: production
