---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cron-insert-secret
  namespace: production
spec:
  encryptedData:
    DATABASE_URL: AgBpM4PVuhFtLd3HDyDbXgapmNeF264Z71y6roriREe+cy3Pw1MatHAKIF/aPDYMs2bzKbC8dxta84iBS7Y24548Klw3yncVyzLSMl19DI2h3eRo9VZ6lzs+KaVtkJ01Hye4JvhJUa/Y6w1BzD5fyC0KJmLObr+/uVCEq75+p0KuDYdlitZhi1rjt5pwRrPvcStZvxqXy3Ev3JyvWr4a68UiExN1QSxy0H1l23/30zGOyZzP3kZaaiseYHBTziWEsm20sd3mFh9giurPP7tBrvoStfup0vFuxY2eyiuTcvgRH+5pFhgt7oazVkW6M5QYgJIbJxQs4g411Ab0Wlf52ZgMyi7X8sAGhutoFTRIABvgViEwzx+j+/wGPpKski0YBYgp52s7Ki4G64FZCmJArBK8qNj4WfTpUqczqLjoaEjO9h9Xg+BrxjFuXigfGqi1KPpwpwM+BdR+TMkrIYPnuvvbn3tgBKJesjhjdKoJfbF9Zc4oLmNnSpXjgGeRLapNwNIKPZPhTrEHljB8m2xlPjQr1mvOrDn4+XrOuegauAWErzulbVqy+yRuwIJuBrTbdjX6VfvPrzMDHbCmlcOrs++jq2Kg3SppOfIYTwrWE1tqvIUhf2q05qj20qzMuV1hgwcfUi+j3W4OW1M+CNq5pQXCyb3jFA21tehU/Y5L/YLb6gKL+VknkGVHzd7WFNyrq6nuuJ8TKN+NMYz4DE8f5Idz4cmXBKT1hHGpntsYEtIexWszYMXnbX1a2CSoi5lOx/8VyQXmGKDSSrtwRM/W9cCxUWlHjz3LrEPYk6gk7djqMGQqAbULTAmERTi8/iTMkPE43GnI9Hk6I3Nw3nKYTl9npKfkJUkMOR7hYmjcjBzDLb7fweAu
  template:
    metadata:
      name: cron-insert-secret
      namespace: production
