---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: production
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgC3UQvodgcdIospuh2IBKtgd8V8qQl+l3+AQ9FI1jxu2k+Y3amlkN/xDgU00npf6SGotNlDkgfINl8LhPpa3Hkbi8XBgp1t8O6gol7kinIbZ/HhYZmJwLMTMpA02zN3esOXFCDKTZX769IPzpMJTRzBOC354yuJOeDBIMLO8eIi6VHgLRAS6gSPRrsHpTCRX5IZN1wvhdV8q+nDi1TVzdeXWjdI7shWjoNBIq/QQENGRgl5A1QX5XTFJCq72IVC54e2Nz5phtENGTMUHDaybDgYsm/kG5l/TQig74FOLct+ud3ZsZ53fZ5NegewQvRej2FsIn3WeADBX4v7QTRzp0dsuidf/UYKv7UAmjKFL6KZbD2Se8Y75BKMRErM7hQE0XQu7L0eyIxuU7lmEdrfgQgQl3KmfirHwTpdKx6WsGCkcOTLbjehNOMnV0U+6w/0SwESKQTpr+9B51E1muVUfOnFIQ8dDFVXSwVPZx4CLf6C9Qhah8CYkuqEcAbxTbdyfETzI0gNLVIN077l6gwLfE2LpFjLBbPDSmwwo0UiVaOTKkzJhWmfJ0ZZu7M02eM4JAzhV7q0yfBHczmgx/PrGbSUkPXCj59e+u5uDMK7EgWKpiY1ODDy2fV1kwLKV7ACAKxN28I4YyALFJLHiMpTLqNQhqFzyuin/BvrHP9y3pdpnsrP5TdKLZ5CD2s0y62wJ9W9u8mIFP6CUWp+gQobxySMStftOVRINobSmTOhU4ffetzvvZGc7Ncx5EBdwk2dSk8=
    RABBITMQ_USER: AgBd+8H65ZFMMSb5xUDYqPA7JTmMhuu6StAwZYwlfKpX9G3hQxgMneWV5iCYsZNvKtmAmeAOCJb/DyxJAQlbdX2Ft716qmnZQADoVZ8QpZuzP4xuFVoxCkl8en40N3F371TZICT2KkjKp+f33a5zCSAOXRkDfvJyysC4wSl/c1iP5hEW0M26BwyMRXoG5sQ7dSOVUjRw4EYnUkg3gVGavJ7+x8BoLNUG3pis8luf+WnwvYDfON0eddUTaEyXQK3OGXoRLCt0uJo7EY3l5UJ7Hq/PbkhmTD5BlKYzCAN74v6pgqRs2yjwFC4rWEju6OUKqENfZ28DpYu6J90KTu2y9jPcGAeuZG3+xatysJ66rFOXYOIcyhEW6gbBBaC8FOFhmG2gPGAI9lDx8z5vF1R0bpVnSXrmWcB9zzwbqq4mUfbbp2EphYfvX4xye1RWbSRXq8e+Et7pv4/W1ZK9UkrGPXfqqksj5yF7LrEL11X3Wex9SorYzKK6Uo8ZWVnTe8f3pUwaiFs6NA+wAupsMzsnyMsRn0PNsgnM5I/1H7MRZZiwqkaKEn344AMFW3KwQU4mp6M4MGvhrykKVSUNsmvZWt+F1+hDDnKDCtk/Kcaae27hit7Kfp+ge64xSkmZM0SiviokF1vDFN4wqlN1sfm1vRHsDjWdQqsMiMOdgdXH31aKr/eIbV5JYy9A8XtkUwAcga32WYoOmgxA
  template:
    metadata:
      name: rabbitmq-secret
      namespace: production
