image:
  repository: postgres
  tag: "17-alpine"
  pullPolicy: IfNotPresent

serviceAccountName: sa-platform
secretName: postgresql-secret

service:
  port: 5432

persistence:
  size: 1Gi
  storageClass: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
