replicaCount: 1
image:
  tag: "1.0.6"
config:
  APP_VERSION: "1.0.6"
  LOG_LEVEL: info
ingress:
  host: sa-p8.local
hpa:
  minReplicas: 1
  maxReplicas: 2
resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi
